#!/usr/bin/env bash

#sudo apt install neovim -y

# From source
mkdir ~/personal
cd ~/personal
git clone -b master --single-branch https://github.com/neovim/neovim.git
cd neovim

sudo apt install cmake gettext lua5.1 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

# Packer
#git clone --depth 1 https://github.com/wbthomason/packer.nvim\
# ~/.local/share/nvim/site/pack/packer/start/packer.nvim
