#!/usr/bin/env bash

# Update repositories
sudo apt update

sudo apt install git -y

sudo apt install curl -y

sudo apt install wget -y

# Install Zsh
sudo apt install zsh -y

# Install Oh My Zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
